models:
- model: cable
  version: main
  fetch_from:
    git:
      url: https://github.com/CABLE-LSM/CABLE
      ref: main
  install_command: |
    cd ${MODEL_SOURCE}
    ./build.bash
  prefix_path: ${MODEL_SOURCE}/bin
- model: cable
  version: gcc_compilation_and_warnings
  install_command: |
    spack install cable@git.gcc_compilation_and_warnings%intel~mpi^netcdf-fortran@4.6.0
  prefix_path_command: |
    spack find --format "{prefix}/bin" cable@git.gcc_compilation_and_warnings%intel~mpi^netcdf-fortran@4.6.0
